kowalski:
  host: gloria.caltech.edu
  port: 443
  protocol: https
  token:
  collections:
    gaia: Gaia_EDR3
    sources: ZTF_sources_20210401
    features: ZTF_source_features_20210401
taxonomy:
  class: tds
  name: time domain source type
  subclasses:
    - class: phenomenological
      name: phenomenological
      description: |
        What can be said about an object given *only* ZTF data.
      subclasses:
        - class: vnv
          name: variable
          description: |
            Any ZTF source that shows detectable variability in its light curve
            due to an astrophysical origin. This excludes variability due to blended photometry,
            bright nearby stars, or any CCD artifact.
        - class: pnp
          name: periodic
          description: |
            The ZTF light curve features astrophysical periodic variability.
            These are typically pulsators, rotating stars and (eclipsing) binaries.
            This does not include semi-periodic or quasi-periodic variability. This
            excludes variability due to a varying background (e.g. due to the moon),
            or spurious periodic variability due to nearby bright stars or other artifacts.
        - class: longt
          name: long timescale
          description: |
            Any object which shows variability on timescales of ~100+ days. This can be a steady
            increase/decrease in luminosity, e.g., AGN and CVs.
            Long timescale period variable like Miras and the more
            irregular semi-regular variables are generally included in this category.
        - class: i
          name: irregular
          description: |
            Objects which show irregular/stochastic variability.
            These are mostly accreting objects, AGN, CVs, and YSOs.
        - class: e
          name: eclipsing
          description: |
            Any source that shows eclipses in the light curve.
            These are predominately eclipsing binaries.
            Eclipsing planetisimals or planets with large rings would also
            fall in this category.
          subclasses:
            - class: ea
              name: detached binary
            - class: eb
              name: semi-detached binary
            - class: ew
              name: overcontact binary
        - class: fla
          name: flaring
          description: |
            Any ZTF light curve that shows flares, rapidly rising and fading events.
            These are mostly cataclysmic variables, some young stellar objects, M-dwarfs, and some AGN.
        - class: bogus
          name: bogus
          description: |
            Any light curve that seems variable, but is not due to any astrophysical variability.
            These are galaxies that can seem to vary due to PSF variations,
            image artifacts like ghosts, blended stars, or diffraction spikes.
    - class: ontological
      name: ontological
      description: |
        What can be said about an object given *not only* ZTF data
      subclasses:
        - class: puls
          name: pulsator
          description: |
            Any kind of pulsating star.
          subclasses:
            - class: dscu
              name: Delta Scuti
              description: |
                Delta Scuti are pulsating A&F main sequence stars. The pulsation period ranges between
                0.03 between 0.3 days, and the amplitude is typically 0.2 mag but can reach up to 0.8mag.
                Their light curves are asymmetric, with a rapid rise and slow decay.
            - class: ceph
              name: Cepheid
              description: |
                Cepheids are radially pulsating giant stars in the instability strip.
                Period range between 1 and 50 days, with extreme examples of 200 days.
                Light curves shapes range from asymmetric with a steep rise
                and slow decay, to almost sinusoidal light curve shapes.
            - class: rrlyr
              name: RR Lyrae
              description: |
                RR Lyrae are radial pulsators on the horizontal branch; they are helium core burning and
                hydrogen shell burning. The pulsation period ranges between 0.2 and 1.0 days.
            - class: lpv
              name: long period variable
              description: |
                Long Period Variables are cool giant stars. Nearly all stars of this type show
                some variability.
              subclasses:
                - class: mira
                  name: Mira
                  description: |
                    AGB stars which show very high amplitude (> 2.5), long period (80-1000
                    days) variability.
                - class: srv
                  name: semi-regulat variable
                  description: |
                    Show more irregular, and lower amplitude variability than Miras.
        - class: bis
          name: binary star
          description: |
            Any object that is a binary star.
          subclasses:
            - class: wuma
              name: W Uma
              description: |
                Eclipsing close binary stars of spectral types F, G, or K that share a common envelope
                of material and are thus in contact with one another.
            - class: blyr
              name: Beta Lyr
              description: |
                Binary systems where one of the components has evolved into a subgiant or giant star and
                is filling its Roche lobe transferring mass in a disk.
                The light curve of these systems is of type EB. The period
                ranges between 0.3 days and 200 days.
                Systems with a period of >100 days contains a supergiant.
            - class: rscvn
              name: RS CVn
              description: |
                A binary star where at least one of the components
                has large stellar spots. The light curve shape is sinusoidal
                with periods of a few hours to 14 days.
                The shape of the light curve changes over timescales of months to years.
        - class: agn
          name: active galactic nuclei
          description: |
            Extra-galactic objects which tend to vary irregularly. Often show slowly rising
            or fading light curves, and can also show outbursts in rare cases.
        - class: yso
          name: young stellar object
          description: |
            Pre-main-sequence stars. They typically have an accretion disk and dust around
            them. This results in a light curve which shows irregular behavior,
            sometimes with outbursts or dust obscuration events.
        - class: cv
          name: cataclysmic variable
          description: |
            A binary star that consists of two components:
            a white dwarf primary, and a mass transferring secondary.

docs:
  field_guide:
    rr_lyr_ab:
      coordinates: [254.9327, 30.8264]
      period: 0.6299307435824886
      title: RR Lyrae ab
    rr_lyr_c:
      coordinates: [254.7213, 32.8341]
      period: 0.31087445597147706
      title: RR Lyrae c
    w_uma:
      coordinates: [270.4229, 7.1722]
      period: 0.26901030387060865
      title: W Uma
    beta_lyr:
      coordinates: [116.79866129999999, 51.4231961]
      period: 1.836431252123213
      title: Beta Lyrae
    delta_scuti:
      coordinates: [279.9154053, 60.7140833]
      period: 0.064050575
      title: Delta Scuti
    cepheid_F:
      coordinates: [ 0.441542, 62.424306 ]
      period: 3.8785736
      title: Fundamental-mode classical Cepheid
    cepheid_F_1:
      coordinates: [ 4.260375, 60.802722 ]
      period: 6.7987667
      title: Fundamental-mode classical Cepheid with a secondary bump
    cepheid_1O:
      coordinates: [ 321.964458, 24.422528 ]
      period: 0.7703319
      title: First-overtone classical Cepheid
    cepheid_F1O:
      coordinates: [ 292.005292, 19.949889 ]
      period: 4.0442931
      title: Double-mode classical Cepheid
    flaring_dwarfnova:
      coordinates: [ 266.8566657, 63.0465916 ]
      title: Dwarf Nova (Flaring)
    flaring_mdwarf:
      coordinates: [ 103.289525, 10.194726 ]
      title: M dwarf (Flaring)
    cv_U_Gem:
      coordinates: [ 18.884181, 37.626534 ]
      title: Cataclysmic variable (U Gem dwarf nova)
    cv_Z_Cam:
      coordinates: [ 269.093260, 2.967803 ]
      title: Cataclysmic variable (Z Cam dwarf nova)
    cv_SU_UMa:
      coordinates: [ 170.883476, 43.288214 ]
      title: Cataclysmic variable (SU UMa/WZ Sge dwarf nova)
    cv_Novalike:
      coordinates: [ 322.961689, 49.233813 ]
      title: Cataclysmic variable (Novalike)
    mira:
      coordinates: [ 9.1523, 68.0221 ]
      period: 212.0066035
      title: A Mira (Long Period Variable)
    periodic:
      coordinates: [ 288.5243027, 1.51191 ]
      period: 0.350072813283344
      title: Periodic variable
    srv:
      coordinates: [ 330.302266, 66.153712 ]
      title: Semi Regular Variable
    variable:
      coordinates: [ 102.5537728, 44.1032507 ]
      title: Variable stars

features:
  phenomenological_d12:
    - ad
    - chi2red
    - f1_a
    - f1_amp
    - f1_b
    - f1_bic
    - f1_phi0
    - f1_power
    - f1_relamp1
    - f1_relamp2
    - f1_relamp3
    - f1_relamp4
    - f1_relphi1
    - f1_relphi2
    - f1_relphi3
    - f1_relphi5
    - f60
    - f70
    - f80
    - f90
    - inv_vonneumannratio
    - iqr
    - median
    - median_abs_dev
    - norm_excess_var
    - norm_peak_to_peak_amp
    - pdot
    - period
    - roms
    - significance
    - skew
    - smallkurt
    - stetson_j
    - stetson_k
    - sw
    - welch_i
    - wmean
    - wstd
    - n_ztf_alerts
    - mean_ztf_alert_braai
  phenomenological:
#    - ra
#    - dec
#    - n
    - median
    - wmean
    - chi2red
    - roms
    - wstd
    - norm_peak_to_peak_amp
    - norm_excess_var
    - median_abs_dev
    - iqr
    - i60r
    - i70r
    - i80r
    - i90r
    - skew
    - smallkurt
    - inv_vonneumannratio
    - welch_i
    - stetson_j
    - stetson_k
    - ad
    - sw
    - n_ztf_alerts
    - mean_ztf_alert_braai
    - period
    - significance
#    - pdot
    - f1_power
    - f1_BIC
    - f1_a
    - f1_b
    - f1_amp
    - f1_phi0
    - f1_relamp1
    - f1_relphi1
    - f1_relamp2
    - f1_relphi2
    - f1_relamp3
    - f1_relphi3
    - f1_relamp4
    - f1_relphi4
  ontological:
#    - ra
#    - dec
    - median
    - wmean
    - chi2red
    - roms
    - wstd
    - norm_peak_to_peak_amp
    - norm_excess_var
    - median_abs_dev
    - iqr
    - i60r
    - i70r
    - i80r
    - i90r
    - skew
    - smallkurt
    - inv_vonneumannratio
    - welch_i
    - stetson_j
    - stetson_k
    - ad
    - sw
    - n_ztf_alerts
    - mean_ztf_alert_braai
    - period
    - significance
#    - pdot
    - f1_power
    - f1_BIC
    - f1_a
    - f1_b
    - f1_amp
    - f1_phi0
    - f1_relamp1
    - f1_relphi1
    - f1_relamp2
    - f1_relphi2
    - f1_relamp3
    - f1_relphi3
    - f1_relamp4
    - f1_relphi4
    - AllWISE__w1mpro
    - AllWISE__w1sigmpro
    - AllWISE__w2mpro
    - AllWISE__w2sigmpro
    - AllWISE__w3mpro
    - AllWISE__w3sigmpro
    - AllWISE__w4mpro
    - AllWISE__w4sigmpro
#    - AllWISE__ph_qual,
    - Gaia_EDR3__phot_g_mean_mag
    - Gaia_EDR3__phot_bp_mean_mag
    - Gaia_EDR3__phot_rp_mean_mag
    - Gaia_EDR3__parallax
    - Gaia_EDR3__parallax_error
    - Gaia_EDR3__pmra
    - Gaia_EDR3__pmra_error
    - Gaia_EDR3__pmdec
    - Gaia_EDR3__pmdec_error
    - Gaia_EDR3__astrometric_excess_noise
    - Gaia_EDR3__phot_bp_rp_excess_factor
    - PS1_DR1__gMeanPSFMag
    - PS1_DR1__gMeanPSFMagErr
    - PS1_DR1__rMeanPSFMag
    - PS1_DR1__rMeanPSFMagErr
    - PS1_DR1__iMeanPSFMag
    - PS1_DR1__iMeanPSFMagErr
    - PS1_DR1__zMeanPSFMag
    - PS1_DR1__zMeanPSFMagErr
    - PS1_DR1__yMeanPSFMag
    - PS1_DR1__yMeanPSFMagErr

feature_stats:
  ad:
    max: 128.18376934997696
    mean: 15.500210193913036
    median: 11.077439282781256
    min: 0.0
    std: 15.876869787253188
  chi2red:
    max: 915.9355215479488
    mean: 128.3734785119306
    median: 81.39580095811127
    min: 0.0
    std: 141.71837464161496
  dec:
    max: 51.3160467
    mean: 36.09300399755001
    median: 36.8089302
    min: 0.8795246000000001
    std: 9.774441269894961
  f1_BIC:
    max: 55545.850088422936
    mean: 2466.9404783859877
    median: 822.497838038317
    min: 0.0
    std: 4973.26501400567
  f1_a:
    max: 20.555081290076835
    mean: 16.7016476151908
    median: 16.808905545435877
    min: 12.561802534093411
    std: 1.5451790092056719
  f1_amp:
    max: 0.5086391352232238
    mean: 0.217913374707297
    median: 0.23480341157808193
    min: 0.0
    std: 0.13105091448217593
  f1_b:
    max: 0.0003119067445411
    mean: -3.984322282271079e-07
    median: -1.7837800409589736e-08
    min: -0.0002287952951165
    std: 3.8427784228192575e-05
  f1_phi0:
    max: 3.138993460297322
    mean: -0.0018522842487696267
    median: 0.0
    min: -3.1400780083030284
    std: 1.807121336859729
  f1_power:
    max: 0.9962069767316708
    mean: 0.8401071604040212
    median: 0.9425674811617903
    min: 0.0
    std: 0.2182178904556876
  f1_relamp1:
    max: 46.89435719328306
    mean: 0.6850419112577885
    median: 0.40608248325283886
    min: 0.0
    std: 2.2585405460162886
  f1_relamp2:
    max: 394.28148711440326
    mean: 1.8991698838142306
    median: 0.2423619985927272
    min: 0.0
    std: 13.857094369730152
  f1_relamp3:
    max: 22.081306157710728
    mean: 0.24558244529297696
    median: 0.1232197188581303
    min: 0.0
    std: 1.1078338394600216
  f1_relamp4:
    max: 11.063213042624032
    mean: 0.1221521309269351
    median: 0.06411365971551705
    min: 0.0
    std: 0.5402419565567578
  f1_relphi1:
    max: 0.993736398642984
    mean: 0.4050974018728539
    median: 0.3847119735369863
    min: 0.0
    std: 0.141933997863902
  f1_relphi2:
    max: 0.9976872040913396
    mean: 0.7412080451618218
    median: 0.8150775412404753
    min: 0.0
    std: 0.2304823244472111
  f1_relphi3:
    max: 0.9958706284435408
    mean: 0.36040667702949725
    median: 0.31471693806758955
    min: 0.0
    std: 0.19600300696741735
  f1_relphi4:
    max: 0.999701975630768
    mean: 0.6402455391773545
    median: 0.708693942657525
    min: 0.0
    std: 0.25954569613825434
  i60r:
    max: 0.7052000000000014
    mean: 0.3208797999999991
    median: 0.3380000000000009
    min: 0.0170000000000012
    std: 0.15884466371886724
  i70r:
    max: 0.8331999999999979
    mean: 0.3726940499999994
    median: 0.3916499999999985
    min: 0.0200000000000013
    std: 0.18558323408136151
  i80r:
    max: 0.9774000000000028
    mean: 0.42838049999999955
    median: 0.4500999999999973
    min: 0.0259999999999998
    std: 0.21430215409498352
  i90r:
    max: 1.1997999999999998
    mean: 0.4903682499999998
    median: 0.515150000000002
    min: 0.0290999999999996
    std: 0.24561823949869332
  inv_vonneumannratio:
    max: 71.60876788752633
    mean: 3.693885089513038
    median: 3.214942762974602
    min: 0.0
    std: 3.5244514681933246
  iqr:
    max: 0.5730000000000004
    mean: 0.27013174999999906
    median: 0.2866249999999999
    min: 0.0139999999999993
    std: 0.13312525475820686
  mean_ztf_alert_braai:
    max: 0.9996429748005338
    mean: 0.8076804129094862
    median: 0.9322394433164628
    min: 0.0
    std: 0.2558913457113731
  median:
    max: 20.622
    mean: 16.7641675
    median: 16.852
    min: 12.631
    std: 1.556161060813999
  median_abs_dev:
    max: 0.2620000000000004
    mean: 0.11066249999999905
    median: 0.1189999999999997
    min: 0.0069999999999996
    std: 0.05087262371600262
  n_ztf_alerts:
    max: 4156
    mean: 877.847
    median: 805.0
    min: 0
    std: 756.8775869260505
  norm_excess_var:
    max: 0.0005371573224967
    mean: 0.00011951194250108002
    median: 9.884821724223116e-05
    min: -7.916986315734908e-06
    std: 9.961048471438293e-05
  norm_peak_to_peak_amp:
    max: 0.0394875714233722
    mean: 0.015503849382685208
    median: 0.016011572515849302
    min: 0.0002135643896635
    std: 0.008481218113689204
#  pdot:
#    max: 0.0
#    mean: 0.0
#    median: 0.0
#    min: 0.0
#    std: 0.0
  period:
    max: 41.45854949951172
    mean: 0.8798234658446163
    median: 0.6010188460350037
    min: 0.0208595860749483
    std: 1.7742063841484774
  ra:
    max: 359.6758769
    mean: 243.90023848085013
    median: 259.935487275
    min: 0.0927373
    std: 77.16145722302882
  roms:
    max: 25.40404040404041
    mean: 8.037975342585083
    median: 7.711046446155909
    min: 0.0
    std: 5.157986092261859
  significance:
    max: 495.15045166015625
    mean: 209.52383236932755
    median: 226.0513458251953
    min: 6.9505791664123535
    std: 116.24504254132405
  skew:
    max: 33.90622720529045
    mean: -1275.2722937263065
    median: -319.2648779654087
    min: -20778.94743165396
    std: 2417.836834216222
  smallkurt:
    max: 1835335.807427644
    mean: 83148.09613130947
    median: 14389.522020117014
    min: -2.643610445299017
    std: 182687.49291080795
  stetson_j:
    max: 5344.182358481043
    mean: 392.5783778720605
    median: 144.0287468842411
    min: -907.609874472811
    std: 704.3506254156605
  stetson_k:
    max: 0.9127880140580223
    mean: 0.8651686878073702
    median: 0.8672275927742372
    min: 0.0
    std: 0.031936696026197295
  sw:
    max: 0.9810750484466552
    mean: 0.8604545010328293
    median: 0.883013904094696
    min: 0.0
    std: 0.10086537409592566
  welch_i:
    max: 152157.98765175126
    mean: 5878.670791277614
    median: 678.9446962980172
    min: -22494.67497745018
    std: 15142.14033375962
  wmean:
    max: 20.513689643924465
    mean: 16.676460156898415
    median: 16.811321928446244
    min: 0.0
    std: 1.6212516062136633
  wstd:
    max: 0.4079925848238782
    mean: 0.16752170745762138
    median: 0.1742450607167353
    min: 0.0
    std: 0.08687656119729947

training:
  dataset: md5 checksum? filename? from GCS? to use for training
  classes:
    agn:
      label: AGN
      # value should refer to features section of this config
      features: ontological
      # our "labels" are floats [0., 0.25, 0.5, 0.75, 1.]
      threshold: 0.7
      # balance ratio for the prevalent class. leave as null to use all available data
      balance: 2.5
      weight_per_class: false
    vnv:
      label: variable
      # value should refer to features section of this config
      features: phenomenological
      # our "labels" are floats [0., 0.25, 0.5, 0.75, 1.]
      threshold: 0.7
      # balance ratio for the prevalent class. leave as null to use all available data
      balance:
      weight_per_class: true
