#!/bin/bash

echo "dnn inference"
echo -n "agn ... "  && python tools/inference.py --path-model=models/dr5-1/agn-20210919_090902.h5   --model-class=agn --field=$1 --whole-field --flag_ids && echo "done"
echo -n "bis ... "  && python tools/inference.py --path-model=models/dr5-1/bis-20210919_140037.h5   --model-class=bis --field=$1 --whole-field && echo "done"
echo -n "blyr ... " && python tools/inference.py --path-model=models/dr5-1/blyr-20210919_184548.h5  --model-class=blyr --field=$1 --whole-field && echo "done"
echo -n "ceph ... " && python tools/inference.py --path-model=models/dr5-1/ceph-20210919_190517.h5  --model-class=ceph --field=$1 --whole-field && echo "done"
echo -n "dscu ... " && python tools/inference.py --path-model=models/dr5-1/dscu-20210919_204537.h5  --model-class=dscu --field=$1 --whole-field && echo "done"
echo -n "e ... "    && python tools/inference.py --path-model=models/dr5-1/e-20210918_225015.h5     --model-class=e --field=$1 --whole-field && echo "done"
echo -n "ea ... "   && python tools/inference.py --path-model=models/dr5-1/ea-20210918_222613.h5    --model-class=ea --field=$1 --whole-field && echo "done"
echo -n "eb ... "   && python tools/inference.py --path-model=models/dr5-1/eb-20210918_214407.h5    --model-class=eb --field=$1 --whole-field && echo "done"
echo -n "ew ... "   && python tools/inference.py --path-model=models/dr5-1/ew-20210918_144924.h5    --model-class=ew --field=$1 --whole-field && echo "done"
echo -n "fla ... "  && python tools/inference.py --path-model=models/dr5-1/fla-20210918_080316.h5   --model-class=fla --field=$1 --whole-field && echo "done"
echo -n "i ... "    && python tools/inference.py --path-model=models/dr5-1/i-20210918_071727.h5     --model-class=i --field=$1 --whole-field && echo "done"
echo -n "longt ... " && python tools/inference.py --path-model=models/dr5-1/longt-20210918_051118.h5 --model-class=longt --field=$1 --whole-field && echo "done"
echo -n "lpv ... "  && python tools/inference.py --path-model=models/dr5-1/lpv-20210919_213033.h5   --model-class=lpv --field=$1 --whole-field && echo "done"
echo -n "pnp ... "  && python tools/inference.py --path-model=models/dr5-1/pnp-20210918_041303.h5   --model-class=pnp --field=$1 --whole-field && echo "done"
echo -n "puls ... " && python tools/inference.py --path-model=models/dr5-1/puls-20210920_012555.h5  --model-class=puls --field=$1 --whole-field && echo "done"
echo -n "rrlyr ... " && python tools/inference.py --path-model=models/dr5-1/rrlyr-20210920_041205.h5 --model-class=rrlyr --field=$1 --whole-field && echo "done"
echo -n "rscvn ... " && python tools/inference.py --path-model=models/dr5-1/rscvn-20210920_045003.h5 --model-class=rscvn --field=$1 --whole-field && echo "done"
echo -n "srv ... "  && python tools/inference.py --path-model=models/dr5-1/srv-20210920_053008.h5   --model-class=srv --field=$1 --whole-field && echo "done"
echo -n "vnv ... "  && python tools/inference.py --path-model=models/dr5-1/vnv-20210915_220725.h5   --model-class=vnv --field=$1 --whole-field && echo "done"
echo -n "yso ... "  && python tools/inference.py --path-model=models/dr5-1/yso-20210920_184534.h5   --model-class=yso --field=$1 --whole-field && echo "done"

echo "xgb inference"
echo -n "agn ... "  && python tools/inference.py --path-model=models/d15.agn.f.model --model-class=agn --xgb-model --field=$1 --whole-field --flag_ids && echo "done"
echo -n "bis ... "  && python tools/inference.py --path-model=models/d15.bis.c.model --model-class=bis --xgb-model --field=$1 --whole-field && echo "done"
echo -n "blyr ... " && python tools/inference.py --path-model=models/d15.blyr.f.model --model-class=blyr --xgb-model --field=$1 --whole-field && echo "done"
echo -n "ceph ... " && python tools/inference.py --path-model=models/d15.ceph.f.model --model-class=ceph --xgb-model --field=$1 --whole-field && echo "done"
echo -n "dscu ... " && python tools/inference.py --path-model=models/d15.dscu.f.model --model-class=dscu --xgb-model --field=$1 --whole-field && echo "done"
echo -n "e ... "    && python tools/inference.py --path-model=models/d15.e.c.model --model-class=e --xgb-model --field=$1 --whole-field && echo "done"
echo -n "ea ... "   && python tools/inference.py --path-model=models/d15.ea.f.model --model-class=ea --xgb-model --field=$1 --whole-field && echo "done"
echo -n "eb ... "   && python tools/inference.py --path-model=models/d15.eb.f.model --model-class=eb --xgb-model --field=$1 --whole-field && echo "done"
echo -n "ew ... "   && python tools/inference.py --path-model=models/d15.ew.f.model --model-class=ew --xgb-model --field=$1 --whole-field && echo "done"
echo -n "fla ... "  && python tools/inference.py --path-model=models/d15.fla.c.model --model-class=fla --xgb-model --field=$1 --whole-field && echo "done"
echo -n "i ... "    && python tools/inference.py --path-model=models/d15.i.c.model --model-class=i --xgb-model --field=$1 --whole-field && echo "done"
# echo -n "longt ... " && python tools/inference.py --path-model=models/d15.model --model-class=longt --xgb-model --field=$1 --whole-field && echo "done"
echo -n "lpv ... "  && python tools/inference.py --path-model=models/d15.lpv.f.model --model-class=lpv --xgb-model --field=$1 --whole-field && echo "done"
echo -n "pnp ... "  && python tools/inference.py --path-model=models/d15.pnp.c.model --model-class=pnp --xgb-model --field=$1 --whole-field && echo "done"
echo -n "puls ... " && python tools/inference.py --path-model=models/d15.puls.c.model --model-class=puls --xgb-model --field=$1 --whole-field && echo "done"
echo -n "rrlyr ... " && python tools/inference.py --path-model=models/d15.rrlyr.f.model --model-class=rrlyr --xgb-model --field=$1 --whole-field && echo "done"
echo -n "rscvn ... " && python tools/inference.py --path-model=models/d15.rscvn.f.model --model-class=rscvn --xgb-model --field=$1 --whole-field && echo "done"
echo -n "srv ... "  && python tools/inference.py --path-model=models/d15.srv.f.model --model-class=srv --xgb-model --field=$1 --whole-field && echo "done"
echo -n "vnv ... "  && python tools/inference.py --path-model=models/d15.vnv.c.model --model-class=vnv --xgb-model --field=$1 --whole-field && echo "done"
echo -n "wuma ... "  && python tools/inference.py --path-model=models/d15.wuma.f.model --model-class=wuma --xgb-model --field=$1 --whole-field && echo "done"
echo -n "yso ... "  && python tools/inference.py --path-model=models/d15.yso.f.model --model-class=yso --xgb-model --field=$1 --whole-field && echo "done"
