#!/bin/bash
# Phenomenological
./scope.py train --tag vnv --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag pnp --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag sin --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag el --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag saw --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag mp --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag longt --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag e --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag ea --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag eb --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag ew --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag wp --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag hp --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag dp --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag i --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag fla --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag dip --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag bogus --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag gal --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag blend --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag bright --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag artfct --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
# Ontological
./scope.py train --tag agn --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag bis --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag blher --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag blyr --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag cbin --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag ceph --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag ceph2 --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag cv --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag dscu --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag emsms --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag f --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag hwvir --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag lpv --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag mira --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag nnser --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag o --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag osarg --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag puls --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag rdbkp --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag rrlyr --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag rrab --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag rrc --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag rrd --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag rrblz --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag rscvn --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag rvtau --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag srv --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag wuma --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
#./scope.py train --tag wvir --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
./scope.py train --tag yso --path_dataset tools/fritzDownload/merged_classifications_features.parquet --verbose
