#!/bin/bash
#SBATCH --job-name=combine_preds.job
#SBATCH --output=combine_preds/logs/combine_preds_%A_%a.out
#SBATCH --error=combine_preds/logs/combine_preds_%A_%a.err
#SBATCH -p shared
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --mem 128G
#SBATCH -A umn131
#SBATCH --time=48:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=warsh029@umn.edu
module purge
source activate scope-env
combine-preds --use-config-fields --write-csv
