#!/usr/bin/env python
import yaml
import os

config_data = {
    'kowalski': {
        'hosts': {
            'kowalski': {'token': None},
            'gloria': {'token': None},
            'melman': {'token': None},
        },
        'port': 443,
        'protocol': 'https',
        'timeout': 300,
        'collections': {
            'gaia': 'Gaia_EDR3',
            'sources': 'ZTF_sources_20230821',
            'features': 'ZTF_source_features_DR16',
            'classifications': 'ZTF_source_classifications_DR16',
            'alerts': 'ZTF_alerts',
        },
        'max_timestamp_hjd': 2459951.5,
    },
    'fritz': {
        'token': None,
        'protocol': 'https',
        'host': 'fritz.science',
        'max_attempts': 10,
        'sleep_time': 5,
    },
    'wandb': {
        'entity': 'ztf-scope',
        'project': 'scope',
        'token': None,
        'sweep_config_dnn': {
            'method': 'bayes',
            'metric': {'goal': 'minimize', 'name': 'val_loss'},
            'run_cap': 10,
            'parameters': {
                'lr': {'min': 0.0003, 'max': 0.03},
                'epsilon': {'min': 1e-09, 'max': 1e-07},
                'amsgrad': {'min': 3e-05, 'max': 0.003},
                'decay': {'value': 0.0},
                'beta_1': {'value': 0.9},
                'beta_2': {'value': 0.999},
                'epochs': {'value': 50},
                'dense_branch': {'value': True},
                'conv_branch': {'value': True},
                'loss': {'value': 'binary_crossentropy'},
                'optimizer': {'value': 'adam'},
                'momentum': {'value': 0.9},
                'monitor': {'value': 'val_loss'},
                'patience': {'value': 20},
                'callbacks': {'value': ['reduce_lr_on_plateau', 'early_stopping']},
                'run_eagerly': {'value': False},
            },
        },
    },
    'taxonomy': {
        'class': 'tds',
        'name': 'time domain source type',
        'subclasses': [
            {
                'class': 'phenomenological',
                'name': 'phenomenological',
                'description': 'What can be said about an object given *only* ZTF data. ',
                'subclasses': [
                    {
                        'class': 'vnv',
                        'name': 'variable',
                        'description': 'Any ZTF source that shows detectable variability in its light curve due to an astrophysical origin. This excludes variability due to blended photometry, bright nearby stars, or any CCD artifact. ',
                    },
                    {
                        'class': 'pnp',
                        'name': 'periodic',
                        'description': 'The ZTF light curve features astrophysical periodic variability. These are typically pulsators, rotating stars and (eclipsing) binaries. This does not include semi-periodic or quasi-periodic variability. This excludes variability due to a varying background (e.g. due to the moon), or spurious periodic variability due to nearby bright stars or other artifacts. ',
                    },
                    {
                        'class': 'longt',
                        'name': 'long timescale',
                        'description': 'Any object which shows variability on timescales of ~100+ days. This can be a steady increase/decrease in luminosity, e.g., AGN and CVs. Long timescale period variable like Miras and the more irregular semi-regular variables are generally included in this category. ',
                    },
                    {
                        'class': 'i',
                        'name': 'irregular',
                        'description': 'Objects which show irregular/stochastic variability. These are mostly accreting objects, AGN, CVs, and YSOs. ',
                    },
                    {
                        'class': 'e',
                        'name': 'eclipsing',
                        'description': 'Any source that shows eclipses in the light curve. These are predominately eclipsing binaries. Eclipsing planetisimals or planets with large rings would also fall in this category. ',
                        'subclasses': [
                            {'class': 'ea', 'name': 'detached binary'},
                            {'class': 'eb', 'name': 'semi-detached binary'},
                            {'class': 'ew', 'name': 'overcontact binary'},
                        ],
                    },
                    {
                        'class': 'fla',
                        'name': 'flaring',
                        'description': 'Any ZTF light curve that shows flares, rapidly rising and fading events. These are mostly cataclysmic variables, some young stellar objects, M-dwarfs, and some AGN. ',
                    },
                    {
                        'class': 'bogus',
                        'name': 'bogus',
                        'description': 'Any light curve that seems variable, but is not due to any astrophysical variability. These are galaxies that can seem to vary due to PSF variations, image artifacts like ghosts, blended stars, or diffraction spikes. ',
                    },
                ],
            },
            {
                'class': 'ontological',
                'name': 'ontological',
                'description': 'What can be said about an object given *not only* ZTF data ',
                'subclasses': [
                    {
                        'class': 'puls',
                        'name': 'pulsator',
                        'description': 'Any kind of pulsating star. ',
                        'subclasses': [
                            {
                                'class': 'dscu',
                                'name': 'Delta Scuti',
                                'description': 'Delta Scuti are pulsating A&F main sequence stars. The pulsation period ranges between 0.03 between 0.3 days, and the amplitude is typically 0.2 mag but can reach up to 0.8mag. Their light curves are asymmetric, with a rapid rise and slow decay. ',
                            },
                            {
                                'class': 'ceph',
                                'name': 'Cepheid',
                                'description': 'Cepheids are radially pulsating giant stars in the instability strip. Period range between 1 and 50 days, with extreme examples of 200 days. Light curves shapes range from asymmetric with a steep rise and slow decay, to almost sinusoidal light curve shapes. ',
                            },
                            {
                                'class': 'rrlyr',
                                'name': 'RR Lyrae',
                                'description': 'RR Lyrae are radial pulsators on the horizontal branch; they are helium core burning and hydrogen shell burning. The pulsation period ranges between 0.2 and 1.0 days. ',
                            },
                            {
                                'class': 'lpv',
                                'name': 'long period variable',
                                'description': 'Long Period Variables are cool giant stars. Nearly all stars of this type show some variability. ',
                                'subclasses': [
                                    {
                                        'class': 'mira',
                                        'name': 'Mira',
                                        'description': 'AGB stars which show very high amplitude (> 2.5), long period (80-1000 days) variability. ',
                                    },
                                    {
                                        'class': 'srv',
                                        'name': 'semi-regulat variable',
                                        'description': 'Show more irregular, and lower amplitude variability than Miras. ',
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        'class': 'bis',
                        'name': 'binary star',
                        'description': 'Any object that is a binary star. ',
                        'subclasses': [
                            {
                                'class': 'wuma',
                                'name': 'W UMa',
                                'description': 'Eclipsing close binary stars of spectral types F, G, or K that share a common envelope of material and are thus in contact with one another. ',
                            },
                            {
                                'class': 'blyr',
                                'name': 'Beta Lyr',
                                'description': 'Binary systems where one of the components has evolved into a subgiant or giant star and is filling its Roche lobe transferring mass in a disk. The light curve of these systems is of type EB. The period ranges between 0.3 days and 200 days. Systems with a period of >100 days contains a supergiant. ',
                            },
                            {
                                'class': 'rscvn',
                                'name': 'RS CVn',
                                'description': 'A binary star where at least one of the components has large stellar spots. The light curve shape is sinusoidal with periods of a few hours to 14 days. The shape of the light curve changes over timescales of months to years. ',
                            },
                        ],
                    },
                    {
                        'class': 'agn',
                        'name': 'active galactic nuclei',
                        'description': 'Extra-galactic objects which tend to vary irregularly. Often show slowly rising or fading light curves, and can also show outbursts in rare cases. ',
                    },
                    {
                        'class': 'yso',
                        'name': 'young stellar object',
                        'description': 'Pre-main-sequence stars. They typically have an accretion disk and dust around them. This results in a light curve which shows irregular behavior, sometimes with outbursts or dust obscuration events. ',
                    },
                    {
                        'class': 'cv',
                        'name': 'cataclysmic variable',
                        'description': 'A binary star that consists of two components: a white dwarf primary, and a mass transferring secondary. ',
                    },
                ],
            },
        ],
    },
    'docs': {
        'field_guide': {
            'rr_lyr_ab': {
                'coordinates': [254.9327, 30.8264],
                'period': 0.6299307435824886,
                'title': 'RR Lyrae ab',
            },
            'rr_lyr_c': {
                'coordinates': [254.7213, 32.8341],
                'period': 0.31087445597147706,
                'title': 'RR Lyrae c',
            },
            'w_uma': {
                'coordinates': [270.4229, 7.1722],
                'period': 0.26901030387060865,
                'title': 'W UMa',
            },
            'beta_lyr': {
                'coordinates': [116.79866129999999, 51.4231961],
                'period': 1.836431252123213,
                'title': 'Beta Lyrae',
            },
            'bogus_1': {
                'coordinates': [328.1595911, 69.6487077],
                'title': "Bogus ``flaring'' from saturation ghosts",
            },
            'bogus_2': {
                'coordinates': [209.584254, 40.4601446],
                'title': "Bogus ``flaring'' from a different artifact",
            },
            'delta_scuti': {
                'coordinates': [279.9154053, 60.7140833],
                'period': 0.064050575,
                'title': 'Delta Scuti',
            },
            'cepheid_F': {
                'coordinates': [0.441542, 62.424306],
                'period': 3.8785736,
                'title': 'Fundamental-mode classical Cepheid',
            },
            'cepheid_F_1': {
                'coordinates': [4.260375, 60.802722],
                'period': 6.7987667,
                'title': 'Fundamental-mode classical Cepheid with a secondary bump',
            },
            'cepheid_1O': {
                'coordinates': [321.964458, 24.422528],
                'period': 0.7703319,
                'title': 'First-overtone classical Cepheid',
            },
            'cepheid_F1O': {
                'coordinates': [292.005292, 19.949889],
                'period': 4.0442931,
                'title': 'Double-mode classical Cepheid',
            },
            'flaring_dwarfnova': {
                'coordinates': [266.8566657, 63.0465916],
                'title': 'Dwarf Nova (Flaring)',
            },
            'flaring_mdwarf': {
                'coordinates': [103.289525, 10.194726],
                'title': 'M dwarf (Flaring)',
            },
            'cv_U_Gem': {
                'coordinates': [18.884181, 37.626534],
                'title': 'Cataclysmic variable (U Gem dwarf nova)',
            },
            'cv_Z_Cam': {
                'coordinates': [269.09326, 2.967803],
                'title': 'Cataclysmic variable (Z Cam dwarf nova)',
            },
            'cv_SU_UMa': {
                'coordinates': [170.883476, 43.288214],
                'title': 'Cataclysmic variable (SU UMa/WZ Sge dwarf nova)',
            },
            'cv_Novalike': {
                'coordinates': [322.961689, 49.233813],
                'title': 'Cataclysmic variable (Novalike)',
            },
            'mira': {
                'coordinates': [9.1523, 68.0221],
                'period': 212.0066035,
                'title': 'A Mira (Long Period Variable)',
            },
            'periodic': {
                'coordinates': [288.5243027, 1.51191],
                'period': 0.350072813283344,
                'title': 'Periodic variable',
            },
            'srv': {
                'coordinates': [330.302266, 66.153712],
                'title': 'Semi Regular Variable',
            },
            'variable': {
                'coordinates': [102.5537728, 44.1032507],
                'title': 'Variable stars',
            },
        }
    },
    'features': {
        'info': {'period_suffix': 'ELS_ECE_EAOV'},
        'phenomenological': {
            'ad': {'include': True, 'dtype': 'float', 'periodic': False},
            'ccd': {'include': False, 'dtype': 'Int64', 'periodic': False},
            'chi2red': {'include': True, 'dtype': 'float', 'periodic': False},
            'dec': {'include': False, 'dtype': 'float', 'periodic': False},
            'f1_BIC': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_a': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_amp': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_b': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_phi0': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_power': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relamp1': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relamp2': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relamp3': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relamp4': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relphi1': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relphi2': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relphi3': {'include': True, 'dtype': 'float', 'periodic': True},
            'f1_relphi4': {'include': True, 'dtype': 'float', 'periodic': True},
            'field': {'include': False, 'dtype': 'Int64', 'periodic': False},
            'i60r': {'include': True, 'dtype': 'float', 'periodic': False},
            'i70r': {'include': True, 'dtype': 'float', 'periodic': False},
            'i80r': {'include': True, 'dtype': 'float', 'periodic': False},
            'i90r': {'include': True, 'dtype': 'float', 'periodic': False},
            'inv_vonneumannratio': {
                'include': True,
                'dtype': 'float',
                'periodic': False,
            },
            'iqr': {'include': True, 'dtype': 'float', 'periodic': False},
            'mean_ztf_alert_braai': {
                'include': False,
                'dtype': 'float',
                'periodic': False,
            },
            'median': {'include': True, 'dtype': 'float', 'periodic': False},
            'median_abs_dev': {'include': True, 'dtype': 'float', 'periodic': False},
            'n': {'include': False, 'dtype': 'float', 'periodic': False},
            'n_ztf_alerts': {'include': False, 'dtype': 'Int64', 'periodic': False},
            'norm_excess_var': {'include': True, 'dtype': 'float', 'periodic': False},
            'norm_peak_to_peak_amp': {
                'include': True,
                'dtype': 'float',
                'periodic': False,
            },
            'pdot': {'include': False, 'dtype': 'float', 'periodic': True},
            'period': {'include': False, 'dtype': 'float', 'periodic': True},
            'quad': {'include': False, 'dtype': 'Int64', 'periodic': False},
            'ra': {'include': False, 'dtype': 'float', 'periodic': False},
            'roms': {'include': True, 'dtype': 'float', 'periodic': False},
            'significance': {'include': False, 'dtype': 'float', 'periodic': True},
            'skew': {'include': True, 'dtype': 'float', 'periodic': False},
            'smallkurt': {'include': True, 'dtype': 'float', 'periodic': False},
            'stetson_j': {'include': True, 'dtype': 'float', 'periodic': False},
            'stetson_k': {'include': True, 'dtype': 'float', 'periodic': False},
            'sw': {'include': True, 'dtype': 'float', 'periodic': False},
            'welch_i': {'include': True, 'dtype': 'float', 'periodic': False},
            'wmean': {'include': True, 'dtype': 'float', 'periodic': False},
            'wstd': {'include': True, 'dtype': 'float', 'periodic': False},
        },
        'ontological': {
            'ad': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'ccd': {
                'include': False,
                'dtype': 'Int64',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'chi2red': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'dec': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'f1_BIC': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_a': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_amp': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_b': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_phi0': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_power': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relamp1': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relamp2': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relamp3': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relamp4': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relphi1': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relphi2': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relphi3': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'f1_relphi4': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'field': {
                'include': False,
                'dtype': 'Int64',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'i60r': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'i70r': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'i80r': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'i90r': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'inv_vonneumannratio': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'iqr': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'mean_ztf_alert_braai': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'zero',
                'periodic': False,
            },
            'median': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'median_abs_dev': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'n': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'n_ztf_alerts': {
                'include': True,
                'dtype': 'Int64',
                'impute_strategy': 'zero',
                'periodic': False,
            },
            'norm_excess_var': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'norm_peak_to_peak_amp': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'pdot': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'period': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'quad': {
                'include': False,
                'dtype': 'Int64',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'ra': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'roms': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'significance': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': True,
            },
            'skew': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'smallkurt': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'stetson_j': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'stetson_k': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'sw': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'welch_i': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'wmean': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'wstd': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'AllWISE___id': {
                'include': False,
                'dtype': 'Int64',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'AllWISE__ph_qual': {
                'include': False,
                'dtype': 'str',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'AllWISE__w1mpro': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'AllWISE__w1sigmpro': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            'AllWISE__w2mpro': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'AllWISE__w2sigmpro': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            'AllWISE__w3mpro': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'AllWISE__w3sigmpro': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'AllWISE__w4mpro': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'AllWISE__w4sigmpro': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'Gaia_EDR3___id': {
                'include': False,
                'dtype': 'Int64',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'Gaia_EDR3__astrometric_excess_noise': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'Gaia_EDR3__parallax': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'Gaia_EDR3__parallax_error': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'Gaia_EDR3__phot_bp_mean_mag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'Gaia_EDR3__phot_bp_rp_excess_factor': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            'Gaia_EDR3__phot_g_mean_mag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'Gaia_EDR3__phot_rp_mean_mag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'Gaia_EDR3__pmdec': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'Gaia_EDR3__pmdec_error': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'Gaia_EDR3__pmra': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'Gaia_EDR3__pmra_error': {
                'include': False,
                'dtype': 'float',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'PS1_DR1___id': {
                'include': False,
                'dtype': 'Int64',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'PS1_DR1__gMeanPSFMag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'PS1_DR1__gMeanPSFMagErr': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            'PS1_DR1__iMeanPSFMag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'PS1_DR1__iMeanPSFMagErr': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            'PS1_DR1__qualityFlag': {
                'include': False,
                'dtype': 'Int64',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'PS1_DR1__rMeanPSFMag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'PS1_DR1__rMeanPSFMagErr': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            'PS1_DR1__yMeanPSFMag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'PS1_DR1__yMeanPSFMagErr': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            'PS1_DR1__zMeanPSFMag': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'regress',
                'periodic': False,
            },
            'PS1_DR1__zMeanPSFMagErr': {
                'include': True,
                'dtype': 'float',
                'impute_strategy': 'median',
                'periodic': False,
            },
            '_id': {
                'include': False,
                'dtype': 'int',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'coordinates': {
                'include': False,
                'dtype': 'object',
                'impute_strategy': 'None',
                'periodic': False,
            },
            'dmdt': {
                'include': False,
                'dtype': 'object',
                'impute_strategy': 'None',
                'periodic': False,
            },
        },
    },
    'feature_stats': {
        'ra': {
            'min': 0.000637,
            'max': 359.9959065,
            'median': 260.57838475,
            'mean': 203.8537195009122,
            'std': 111.29524619256385,
        },
        'dec': {
            'min': -27.97669295,
            'max': 80.12096305,
            'median': 35.74461235,
            'mean': 33.8050848864133,
            'std': 24.53928644472575,
        },
        'ccd': {
            'min': 1,
            'max': 16,
            'median': 10.0,
            'mean': 8.9215225842098,
            'std': 4.407593218358259,
        },
        'quad': {
            'min': 1,
            'max': 4,
            'median': 2.0,
            'mean': 2.474682794956292,
            'std': 1.11338706658081,
        },
        'field': {
            'min': 250,
            'max': 876,
            'median': 683.0,
            'mean': 658.9159381968151,
            'std': 146.04044551816344,
        },
        'median': {
            'min': 11.859,
            'max': 21.7355,
            'median': 17.192999999999998,
            'mean': 17.198497876180767,
            'std': 1.984417549587372,
        },
        'wmean': {
            'min': 0.0,
            'max': 21.72580234909332,
            'median': 17.190525885310052,
            'mean': 17.194469189756948,
            'std': 1.9724064028988926,
        },
        'chi2red': {
            'min': 0.0,
            'max': 14504.867568350095,
            'median': 8.349023359399014,
            'mean': 43.90164979812083,
            'std': 252.59980815489058,
        },
        'roms': {
            'min': 0.0,
            'max': 114.51620270036064,
            'median': 2.390460752111644,
            'mean': 3.6660180168808383,
            'std': 4.379744545440027,
        },
        'wstd': {
            'min': 0.0,
            'max': 2.255608626306496,
            'median': 0.0875371400495776,
            'mean': 0.09811229869829607,
            'std': 0.08429406100213001,
        },
        'norm_peak_to_peak_amp': {
            'min': -0.0026624340791561,
            'max': 0.1968704723268617,
            'median': 0.0067790238702771,
            'mean': 0.008094121375282185,
            'std': 0.008743865061694922,
        },
        'norm_excess_var': {
            'min': -0.000112900619492,
            'max': 0.0609204201612541,
            'median': 1.769738951325714e-05,
            'mean': 7.146689144239448e-05,
            'std': 0.0007345666165872003,
        },
        'median_abs_dev': {
            'min': 0.0030000000000001,
            'max': 1.8210000000000013,
            'median': 0.0659999999999989,
            'mean': 0.07190794059530176,
            'std': 0.06233962602348945,
        },
        'iqr': {
            'min': 0.0060000000000002,
            'max': 4.503,
            'median': 0.141,
            'mean': 0.15836848656470792,
            'std': 0.14571166540496608,
        },
        'i60r': {
            'min': 0.0085999999999994,
            'max': 4.783999999999999,
            'median': 0.1716000000000015,
            'mean': 0.19276104619501683,
            'std': 0.17420744789781734,
        },
        'i70r': {
            'min': 0.0109999999999992,
            'max': 5.121999999999998,
            'median': 0.2028000000000034,
            'mean': 0.22859205687634082,
            'std': 0.2035872239632559,
        },
        'i80r': {
            'min': 0.0129999999999999,
            'max': 5.510200000000001,
            'median': 0.2355999999999998,
            'mean': 0.26673144380824426,
            'std': 0.23485124406618516,
        },
        'i90r': {
            'min': 0.0149999999999987,
            'max': 5.943899999999999,
            'median': 0.2728499999999982,
            'mean': 0.3086220097322302,
            'std': 0.26757399787961367,
        },
        'skew': {
            'min': -2313631.3289482933,
            'max': 991099.7040389637,
            'median': 2.205022682495793,
            'mean': 61.31085516410248,
            'std': 11255.873862484796,
        },
        'smallkurt': {
            'min': -3.11887814831396,
            'max': 972157474.9911993,
            'median': 158.06917554356693,
            'mean': 131691.3802343864,
            'std': 4342921.268698039,
        },
        'inv_vonneumannratio': {
            'min': 0.0,
            'max': 9391.44532323455,
            'median': 0.6565422687368709,
            'mean': 4.93473533396986,
            'std': 81.77941050819155,
        },
        'welch_i': {
            'min': -56346.08384684319,
            'max': 4493321.414933997,
            'median': 5.7813606990069095,
            'mean': 2267.616080217704,
            'std': 47873.865854501935,
        },
        'stetson_j': {
            'min': -1609.5878099366153,
            'max': 43589.80955987325,
            'median': 5.442137093176486,
            'mean': 72.9671030784923,
            'std': 636.9630033716279,
        },
        'stetson_k': {
            'min': 0.0,
            'max': 0.9900279161401804,
            'median': 0.8495064736265487,
            'mean': 0.8452080085034379,
            'std': 0.04080279802330599,
        },
        'ad': {
            'min': 0.0,
            'max': 176.17630087537145,
            'median': 4.829378125197593,
            'mean': 11.05490766018392,
            'std': 16.348165501152252,
        },
        'sw': {
            'min': 0.0,
            'max': 0.9927340149879456,
            'median': 0.9054134488105774,
            'mean': 0.8523579384039067,
            'std': 0.13993721180508925,
        },
        'n_ztf_alerts': {
            'min': 0,
            'max': 4723,
            'median': 107.0,
            'mean': 303.7225303791757,
            'std': 463.8160278824898,
        },
        'mean_ztf_alert_braai': {
            'min': 0.0,
            'max': 1.0,
            'median': 0.8024972106227093,
            'mean': 0.6186727091350507,
            'std': 0.399777890607977,
        },
        'period': {
            'min': 0.0208335053175687,
            'max': 517.5360717773438,
            'median': 0.1684057712554931,
            'mean': 6.364124402270989,
            'std': 41.949603601179156,
        },
        'significance': {
            'min': 6.118862628936768,
            'max': 624.5211181640625,
            'median': 58.54999923706055,
            'mean': 114.21896548587495,
            'std': 127.5865875752379,
        },
        'f1_power': {
            'min': 0.0,
            'max': 0.9991801222326536,
            'median': 0.7729513576206686,
            'mean': 0.5856637777642174,
            'std': 0.39012498079263525,
        },
        'f1_BIC': {
            'min': 0.0,
            'max': 2891387.504941375,
            'median': 230.87496827341926,
            'mean': 999.6595511797041,
            'std': 14770.393366693705,
        },
        'f1_a': {
            'min': 11.605038108855526,
            'max': 35.47802516000542,
            'median': 17.204367321227384,
            'mean': 17.207453638187303,
            'std': 1.9754009492673177,
        },
        'f1_b': {
            'min': -0.0081851219151183,
            'max': 0.0062801395065665,
            'median': 2.0085760689046505e-07,
            'mean': 3.4800597779789258e-06,
            'std': 7.780194814337619e-05,
        },
        'f1_amp': {
            'min': -9.887075962261807,
            'max': 13.924309960344583,
            'median': 0.0,
            'mean': 0.00030681938973214007,
            'std': 0.13155946866638166,
        },
        'f1_phi0': {
            'min': -11.724438770554938,
            'max': 29.653066320859114,
            'median': 0.0,
            'mean': -5.380212391896144e-05,
            'std': 0.13836656908106604,
        },
        'f1_relamp1': {
            'min': -18.83303491356885,
            'max': 7.879818700280141,
            'median': 0.0,
            'mean': 0.00016760276739433792,
            'std': 0.07498279319084965,
        },
        'f1_relphi1': {
            'min': -10.364638619695516,
            'max': 9.954031288887238,
            'median': 0.0,
            'mean': -0.00019264295360274503,
            'std': 0.07278466428116556,
        },
        'f1_relamp2': {
            'min': -6.975813530902832,
            'max': 4.871874483725203,
            'median': 0.0,
            'mean': 0.00011113187232755609,
            'std': 0.043310560007686544,
        },
        'f1_relphi2': {
            'min': -10.400297029937953,
            'max': 6.570057847623894,
            'median': 0.0,
            'mean': 1.0872106471319056e-05,
            'std': 0.05059444662093973,
        },
        'f1_relamp3': {
            'min': -2.6981900071250675,
            'max': 3.781430338071792,
            'median': 0.0,
            'mean': 9.560206262050944e-06,
            'std': 0.029455447659825662,
        },
        'f1_relphi3': {
            'min': -3.620249993449979,
            'max': 2.427014067940686,
            'median': 0.0,
            'mean': -1.4567874903282583e-05,
            'std': 0.03084918708847871,
        },
        'f1_relamp4': {
            'min': -1.5591887740444768,
            'max': 3.3654605530559376,
            'median': 0.0,
            'mean': 2.200771291810491e-05,
            'std': 0.021579957892031404,
        },
        'f1_relphi4': {
            'min': -1.3925247531097054,
            'max': 3.512580595735894,
            'median': 0.0,
            'mean': -3.106283403481359e-05,
            'std': 0.021489003829155504,
        },
        'AllWISE__w1mpro': {
            'min': -0.64,
            'max': 18.55,
            'median': 13.375,
            'mean': 10.39146157663123,
            'std': 6.336729280993646,
        },
        'AllWISE__w1sigmpro': {
            'min': 0.0,
            'max': 0.541,
            'median': 0.025,
            'mean': 0.02828977736064503,
            'std': 0.029680655722442908,
        },
        'AllWISE__w2mpro': {
            'min': -1.027,
            'max': 18.371,
            'median': 13.38,
            'mean': 10.416712919083375,
            'std': 6.358968070465865,
        },
        'AllWISE__w2sigmpro': {
            'min': 0.0,
            'max': 0.5429999999999999,
            'median': 0.0289999999999999,
            'mean': 0.05173096333452405,
            'std': 0.07441618446166971,
        },
        'AllWISE__w3mpro': {
            'min': -2.966,
            'max': 13.961,
            'median': 12.18,
            'mean': 9.032498107488976,
            'std': 5.40822315450349,
        },
        'AllWISE__w3sigmpro': {
            'min': 0.0,
            'max': 0.5429999999999999,
            'median': 0.0,
            'mean': 0.055817588047942596,
            'std': 0.12963007750540897,
        },
        'AllWISE__w4mpro': {
            'min': -3.4930000000000003,
            'max': 10.353,
            'median': 8.818,
            'mean': 6.599634083670247,
            'std': 3.930799975558018,
        },
        'AllWISE__w4sigmpro': {
            'min': 0.0,
            'max': 0.5429999999999999,
            'median': 0.0,
            'mean': 0.013956541473697027,
            'std': 0.07262771279115897,
        },
        'Gaia_EDR3__astrometric_excess_noise': {
            'min': 0.0,
            'max': 159.00471000000002,
            'median': 0.0,
            'mean': 0.4413401196481314,
            'std': 2.654617484408687,
        },
        'Gaia_EDR3__parallax': {
            'min': -22.923777811496677,
            'max': 46.29583797406394,
            'median': 0.3582558286094884,
            'mean': 0.5084082090602149,
            'std': 0.8450879304094892,
        },
        'Gaia_EDR3__parallax_error': {
            'min': 0.0,
            'max': 3.9449198,
            'median': 0.06740824,
            'mean': 0.12593136954772724,
            'std': 0.17324536501697696,
        },
        'Gaia_EDR3__phot_bp_mean_mag': {
            'min': 0.0,
            'max': 24.21375,
            'median': 17.42191,
            'mean': 17.10962581305227,
            'std': 3.113212898074037,
        },
        'Gaia_EDR3__phot_bp_rp_excess_factor': {
            'min': 0.0,
            'max': 163.73576,
            'median': 1.244185,
            'mean': 1.3158426238751653,
            'std': 1.0058780240460925,
        },
        'Gaia_EDR3__phot_g_mean_mag': {
            'min': 0.0,
            'max': 22.020529,
            'median': 16.873185999999997,
            'mean': 16.556365949973124,
            'std': 2.9032751923604057,
        },
        'Gaia_EDR3__phot_rp_mean_mag': {
            'min': 0.0,
            'max': 22.126274,
            'median': 16.166319,
            'mean': 15.811470105575822,
            'std': 2.8546598354464647,
        },
        'Gaia_EDR3__pmdec': {
            'min': -327.72186458913035,
            'max': 360.8625803334337,
            'median': -2.459304207403531,
            'mean': -3.4039371930688382,
            'std': 6.292282926685255,
        },
        'Gaia_EDR3__pmdec_error': {
            'min': 0.0,
            'max': 2.9573073,
            'median': 0.06420316,
            'mean': 0.12223972343607999,
            'std': 0.17578232423936574,
        },
        'Gaia_EDR3__pmra': {
            'min': -445.8502233328984,
            'max': 411.0655015198922,
            'median': -0.7855059678934171,
            'mean': -0.9401638846246996,
            'std': 6.396205073636185,
        },
        'Gaia_EDR3__pmra_error': {
            'min': 0.0,
            'max': 3.0488079,
            'median': 0.07042039,
            'mean': 0.13286379004737364,
            'std': 0.1853519241832836,
        },
        'PS1_DR1__gMeanPSFMag': {
            'min': 0.0,
            'max': 27.992001,
            'median': 17.5881,
            'mean': 17.385813641764923,
            'std': 2.998618558799227,
        },
        'PS1_DR1__gMeanPSFMagErr': {
            'min': 0.0,
            'max': 0.4762149999999999,
            'median': 0.0162705005,
            'mean': 0.02560849714412246,
            'std': 0.030294569909108778,
        },
        'PS1_DR1__iMeanPSFMag': {
            'min': 0.0,
            'max': 21.8801,
            'median': 16.6315,
            'mean': 16.548635769405635,
            'std': 2.0492561358125423,
        },
        'PS1_DR1__iMeanPSFMagErr': {
            'min': 0.0,
            'max': 0.483466,
            'median': 0.010936,
            'mean': 0.016503628403760233,
            'std': 0.019215705218350018,
        },
        'PS1_DR1__qualityFlag': {
            'min': 0.0,
            'max': 174.0,
            'median': 60.0,
            'mean': 58.39407705445202,
            'std': 11.330792461922785,
        },
        'PS1_DR1__rMeanPSFMag': {
            'min': 0.0,
            'max': 22.238001,
            'median': 16.9951,
            'mean': 16.936967671590995,
            'std': 2.1596557453476377,
        },
        'PS1_DR1__rMeanPSFMagErr': {
            'min': 0.0,
            'max': 0.48713499,
            'median': 0.012881,
            'mean': 0.019732657415647375,
            'std': 0.02306842342675604,
        },
        'PS1_DR1__yMeanPSFMag': {
            'min': 0.0,
            'max': 21.304199,
            'median': 16.280001000000002,
            'mean': 16.047748625891675,
            'std': 2.411650378146079,
        },
        'PS1_DR1__yMeanPSFMagErr': {
            'min': 0.0,
            'max': 0.48370799,
            'median': 0.0145479999999999,
            'mean': 0.022344817664936102,
            'std': 0.026862078598248854,
        },
        'PS1_DR1__zMeanPSFMag': {
            'min': 0.0,
            'max': 21.770599,
            'median': 16.448,
            'mean': 16.325237993652525,
            'std': 2.086329999522018,
        },
        'PS1_DR1__zMeanPSFMagErr': {
            'min': 0.0,
            'max': 0.49948201,
            'median': 0.011866,
            'mean': 0.01834675346206806,
            'std': 0.021816145036886694,
        },
    },
    'feature_generation': {
        'path_to_features': None,
        'dataset': 'tools/fritzDownload/merged_classifications_features.parquet',
        'ids_skipGaia': 'specific_ids_dropCloseSources.json',
        'period_algorithms': {'CPU': ['LS', 'CE'], 'GPU': ['ELS', 'ECE', 'EAOV']},
        'fields_to_run': [296],
        'cesium_features': [
            'avg_err',
            'med_err',
            'std_err',
            'total_time',
            'avgt',
            'cads_std',
            'mean',
            'cads_avg',
            'cads_med',
            'cad_probs_1',
            'cad_probs_10',
            'cad_probs_20',
            'cad_probs_30',
            'cad_probs_40',
            'cad_probs_50',
            'cad_probs_100',
            'cad_probs_500',
            'cad_probs_1000',
            'cad_probs_5000',
            'cad_probs_10000',
            'cad_probs_50000',
            'cad_probs_100000',
            'cad_probs_500000',
            'cad_probs_1000000',
            'cad_probs_5000000',
            'cad_probs_10000000',
            'med_double_to_single_step',
            'avg_double_to_single_step',
            'std_double_to_single_step',
            'all_times_nhist_numpeaks',
            'all_times_nhist_peak_val',
            'all_times_nhist_peak_1_to_2',
            'all_times_nhist_peak_1_to_3',
            'all_times_nhist_peak_2_to_3',
            'all_times_nhist_peak_1_to_4',
            'all_times_nhist_peak_2_to_4',
            'all_times_nhist_peak_3_to_4',
            'all_times_nhist_peak1_bin',
            'all_times_nhist_peak2_bin',
            'all_times_nhist_peak3_bin',
            'all_times_nhist_peak4_bin',
            'amplitude',
            'flux_percentile_ratio_mid20',
            'flux_percentile_ratio_mid35',
            'flux_percentile_ratio_mid50',
            'flux_percentile_ratio_mid65',
            'flux_percentile_ratio_mid80',
            'max_slope',
            'maximum',
            'minimum',
            'percent_amplitude',
            'percent_beyond_1_std',
            'percent_close_to_median',
            'percent_difference_flux_percentile',
            'period_fast',
            'qso_log_chi2_qsonu',
            'qso_log_chi2nuNULL_chi2nu',
            'skew',
            'std',
        ],
        'external_catalog_features': {
            'AllWISE': {
                'filter': {},
                'projection': {
                    '_id': 1,
                    'w1mpro': 1,
                    'w1sigmpro': 1,
                    'w2mpro': 1,
                    'w2sigmpro': 1,
                    'w3mpro': 1,
                    'w3sigmpro': 1,
                    'w4mpro': 1,
                    'w4sigmpro': 1,
                    'ph_qual': 1,
                },
            },
            'Gaia_EDR3': {
                'filter': {},
                'projection': {
                    '_id': 1,
                    'phot_g_mean_mag': 1,
                    'phot_bp_mean_mag': 1,
                    'phot_rp_mean_mag': 1,
                    'parallax': 1,
                    'parallax_error': 1,
                    'pmra': 1,
                    'pmra_error': 1,
                    'pmdec': 1,
                    'pmdec_error': 1,
                    'astrometric_excess_noise': 1,
                    'phot_bp_rp_excess_factor': 1,
                },
            },
            'PS1_DR1': {
                'filter': {},
                'projection': {
                    '_id': 1,
                    'gMeanPSFMag': 1,
                    'gMeanPSFMagErr': 1,
                    'rMeanPSFMag': 1,
                    'rMeanPSFMagErr': 1,
                    'iMeanPSFMag': 1,
                    'iMeanPSFMagErr': 1,
                    'zMeanPSFMag': 1,
                    'zMeanPSFMagErr': 1,
                    'yMeanPSFMag': 1,
                    'yMeanPSFMagErr': 1,
                    'qualityFlag': 1,
                },
            },
        },
        'dmdt_ints': {
            'dmints': [
                -8,
                -4.5,
                -3,
                -2.5,
                -2,
                -1.5,
                -1.25,
                -0.75,
                -0.5,
                -0.3,
                -0.2,
                -0.1,
                -0.05,
                0,
                0.05,
                0.1,
                0.2,
                0.3,
                0.5,
                0.75,
                1.25,
                1.5,
                2,
                2.5,
                3,
                4.5,
                8,
            ],
            'dtints': [
                0.0,
                0.02759,
                0.04,
                0.08,
                0.12,
                0.3,
                0.75,
                1,
                1.5,
                2.5,
                3.5,
                4.5,
                5.5,
                7,
                10,
                20,
                30,
                45,
                60,
                90,
                120,
                180,
                240,
                360,
                500,
                650,
                2000,
            ],
        },
    },
    'training': {
        'dataset': 'tools/fritzDownload/merged_classifications_features.parquet',
        'xgboost': {
            'gridsearch_params_start_stop_step': {
                'max_depth': [3, 8, 2],
                'min_child_weight': [1, 6, 2],
                'subsample': [6, 11, 2],
                'colsample_bytree': [6, 11, 2],
            },
            'other_training_params': {
                'eta': [0.3, 0.2, 0.1, 0.05],
                'seed': 42,
                'nfold': 5,
                'metrics': ['auc'],
                'objective': 'binary:logistic',
                'eval_metric': 'auc',
                'early_stopping_rounds': 10,
                'num_boost_round': 999,
            },
        },
        'classes': {
            'vnv': {
                'label': 'variable',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.0003724,
                'epsilon': 1.945e-08,
                'lr': 0.02229,
            },
            'pnp': {
                'label': 'periodic',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.0009233,
                'epsilon': 4.624e-08,
                'lr': 0.001016,
            },
            'sin': {
                'label': 'sinusoidal',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 32,
                'amsgrad': 0.0003503,
                'epsilon': 2.377e-09,
                'lr': 0.01362,
            },
            'el': {
                'label': 'ellipsoidal',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 16,
                'amsgrad': 0.001602,
                'epsilon': 2.08e-08,
                'lr': 0.003313,
            },
            'saw': {
                'label': 'sawtooth',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 16,
                'amsgrad': 0.002117,
                'epsilon': 2.617e-08,
                'lr': 0.006019,
            },
            'mp': {
                'label': 'multi periodic',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.0009331,
                'epsilon': 7.763e-08,
                'lr': 0.02553,
            },
            'longt': {
                'label': 'long timescale',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.002464,
                'epsilon': 7.828e-08,
                'lr': 0.0157,
            },
            'e': {
                'label': 'eclipsing',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.000508,
                'epsilon': 9.878e-08,
                'lr': 0.009592,
            },
            'ea': {
                'label': 'EA',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
                'batch_size': 32,
                'amsgrad': 0.002106,
                'epsilon': 3.393e-08,
                'lr': 0.02956,
            },
            'eb': {
                'label': 'EB',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 32,
                'amsgrad': 0.001482,
                'epsilon': 2.91e-08,
                'lr': 0.008546,
            },
            'ew': {
                'label': 'EW',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.0007208,
                'epsilon': 8.521e-08,
                'lr': 0.01169,
            },
            'wp': {
                'label': 'wrong period',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 8,
                'amsgrad': 0.001258,
                'epsilon': 3.656e-09,
                'lr': 0.02745,
            },
            'hp': {
                'label': 'half period',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.001203,
                'epsilon': 2.178e-08,
                'lr': 0.02022,
            },
            'dp': {
                'label': 'double period',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.002407,
                'epsilon': 3.069e-08,
                'lr': 0.02491,
            },
            'i': {
                'label': 'irregular',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.001389,
                'epsilon': 6.62e-08,
                'lr': 0.008913,
            },
            'fla': {
                'label': 'flaring',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 32,
                'amsgrad': 0.0005241,
                'epsilon': 1.414e-08,
                'lr': 0.01857,
            },
            'dip': {
                'label': 'dipping',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 2,
                'amsgrad': 0.001263,
                'epsilon': 6.249e-08,
                'lr': 0.01326,
            },
            'bogus': {
                'label': 'bogus',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 16,
                'amsgrad': 0.001224,
                'epsilon': 6.559e-08,
                'lr': 0.02439,
            },
            'ext': {
                'label': 'extended',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 2,
                'amsgrad': 0.002583,
                'epsilon': 6.738e-09,
                'lr': 0.001791,
            },
            'blend': {
                'label': 'blend',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.0006385,
                'epsilon': 5.348e-08,
                'lr': 0.02108,
            },
            'bright': {
                'label': 'bright star',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.0004591,
                'epsilon': 3.367e-08,
                'lr': 0.01797,
            },
            'artfct': {
                'label': 'ccd artifact',
                'features': 'phenomenological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'agn': {
                'label': 'AGN',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.0001084,
                'epsilon': 2.791e-08,
                'lr': 0.01955,
            },
            'bis': {
                'label': 'binary star',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.002084,
                'epsilon': 4.453e-08,
                'lr': 0.01773,
            },
            'blher': {
                'label': 'BL Her',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 2,
                'amsgrad': 0.00283,
                'epsilon': 7.96e-08,
                'lr': 0.01647,
            },
            'blyr': {
                'label': 'Beta Lyr',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 32,
                'amsgrad': 0.002989,
                'epsilon': 5.096e-08,
                'lr': 0.0238,
            },
            'cbin': {
                'label': 'compact binary',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'ceph': {
                'label': 'Cepheid',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 16,
                'amsgrad': 0.0003948,
                'epsilon': 6.115e-08,
                'lr': 0.01887,
            },
            'ceph2': {
                'label': 'Cepheid type-II',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.002885,
                'epsilon': 3.463e-08,
                'lr': 0.0006554,
            },
            'cv': {
                'label': 'CV',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.001594,
                'epsilon': 4.78e-08,
                'lr': 0.02281,
            },
            'dscu': {
                'label': 'Delta Scu',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 3.541e-05,
                'epsilon': 2.91e-09,
                'lr': 0.02856,
            },
            'emsms': {
                'label': 'detached eclipsing MS-MS',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.002309,
                'epsilon': 7.012e-08,
                'lr': 0.0242,
            },
            'f': {
                'label': 'F',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'hwvir': {
                'label': 'eclipsing sdB+dM (HW Vir)',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'lpv': {
                'label': 'LPV',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.0004493,
                'epsilon': 9.229e-08,
                'lr': 0.01127,
            },
            'mir': {
                'label': 'Mira',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.0004852,
                'epsilon': 9.688e-08,
                'lr': 0.02416,
            },
            'nnser': {
                'label': 'eclipsing WD+dM (NN Ser)',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'o': {
                'label': 'O',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'osarg': {
                'label': 'OSARG',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 32,
                'amsgrad': 0.001104,
                'epsilon': 8.725e-08,
                'lr': 0.01476,
            },
            'puls': {
                'label': 'pulsator',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.000611,
                'epsilon': 3.289e-08,
                'lr': 0.02658,
            },
            'rdbkp': {
                'label': 'Redback pulsar',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'rrlyr': {
                'label': 'RR Lyrae',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.001245,
                'epsilon': 4.84e-08,
                'lr': 0.02868,
            },
            'rrab': {
                'label': 'RR Lyrae ab',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.001047,
                'epsilon': 4.307e-08,
                'lr': 0.01685,
            },
            'rrc': {
                'label': 'RR Lyrae c',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.002501,
                'epsilon': 7.619e-08,
                'lr': 0.02491,
            },
            'rrd': {
                'label': 'RR Lyrae d',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 4,
                'amsgrad': 0.001336,
                'epsilon': 8.316e-08,
                'lr': 0.02657,
            },
            'rrblz': {
                'label': 'RR Lyrae Blazhko',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 2,
                'amsgrad': 0.002507,
                'epsilon': 1.744e-08,
                'lr': 0.01402,
            },
            'rscvn': {
                'label': 'RS CVn',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 16,
                'amsgrad': 0.002394,
                'epsilon': 3.469e-08,
                'lr': 0.01449,
            },
            'rvtau': {
                'label': 'RV Tau',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': True,
            },
            'srv': {
                'label': 'SRV',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 8,
                'amsgrad': 0.001237,
                'epsilon': 7.951e-08,
                'lr': 0.02222,
            },
            'wuma': {
                'label': 'W UMa',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.001844,
                'epsilon': 4.736e-08,
                'lr': 0.01615,
            },
            'wvir': {
                'label': 'W Virginis',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'batch_size': 2,
                'amsgrad': 0.000135,
                'epsilon': 8.731e-08,
                'lr': 0.02813,
            },
            'yso': {
                'label': 'YSO',
                'features': 'ontological',
                'threshold': 0.7,
                'balance': None,
                'weight_per_class': False,
                'amsgrad': 0.0009407,
                'epsilon': 3.372e-08,
                'lr': 0.02622,
            },
        },
    },
    'inference': {'fields_to_run': [296], 'path_to_preds': None},
}

with open('config.defaults.yaml', 'w') as file:
    yaml.dump(config_data, file, sort_keys=False)
print("Configuration saved to config.defaults.yaml")

config_exists = os.path.isfile('config.yaml')
if not config_exists:
    with open('config.yaml', 'w') as file:
        yaml.dump(config_data, file, sort_keys=False)
    print("Configuration copied to config.yaml. Edit this file to set configs")
else:
    print("config.yaml exists already")
