#!/bin/bash
# Phenomenological
./scope.py train --tag=vnv --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=pnp --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=sin --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=el --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=saw --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=mp --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=longt --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=e --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=ea --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=eb --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=ew --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=wp --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=hp --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=dp --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=i --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=fla --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=dip --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=bogus --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=ext --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=blend --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=bright --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
# Ontological
./scope.py train --tag=agn --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=bis --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=blher --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=blyr --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=ceph --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=ceph2 --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=cv --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=dscu --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=emsms --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=lpv --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=mir --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=osarg --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=puls --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=rrlyr --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=rrab --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=rrc --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=rrd --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=rrblz --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=rscvn --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=srv --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=wuma --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=wvir --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
./scope.py train --tag=yso --algorithm=dnn --path_dataset=fritzDownload/training_set.parquet --period_suffix=ELS_ECE_EAOV --verbose --save --plot --group=trained_dnn_models --gpu=0 --epochs=200
