name: lint

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Set up pre-commit
        run: |
          pip install pre-commit
          pre-commit install
      - name: Lint sources
        run: |
          pre-commit run --all-files
