name: Run test suite

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies and use default config
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        cp config.defaults.yaml config.yaml
        ./scope.py develop

    - name: Run tests
      env:
        KOWALSKI_TOKEN: ${{ secrets.KOWALSKI_TOKEN }}
      run: |
        ./scope.py test
