name: Run test suite

on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  approve: # First step
    runs-on: ubuntu-latest
    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be cleared before running any automated CI.

  test:
    runs-on: ubuntu-latest
    needs: [approve]
    environment:
      name: Integrate Pull Request # dummy environment
    timeout-minutes: 20
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies and use default config
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        cp config.defaults.yaml config.yaml
        ./scope.py develop

    - name: Run tests
      env:
        DUMMY_TOKEN: ${{ secrets.DUMMY_TOKEN }}
        #KOWALSKI_TOKEN: ${{ secrets.KOWALSKI_TOKEN }}
        #KOWALSKI_ALT_TOKEN: ${{ secrets.KOWALSKI_ALT_TOKEN }}
      run: |
        ./scope.py test
