name: Run test suite

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
jobs:
  request_clearance: # First step
    runs-on: ubuntu-latest
    steps:
    - name: Request clearance
      run: echo For security reasons, all pull requests need to be cleared before running any automated CI involving tokens.

  test:
    runs-on: ubuntu-latest
    needs: [request_clearance]
    environment:
      name: Integrate Pull Request # dummy environment
    timeout-minutes: 20
    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and use default config
      run: |
        python -m pip install --upgrade pip
        pip install wheel poetry
        poetry install
        cp config.defaults.yaml config.yaml
        scope-develop

    - name: Run tests
      env:
        KOWALSKI_INSTANCE_TOKEN: ${{ secrets.KOWALSKI_INSTANCE_TOKEN }}
        GLORIA_INSTANCE_TOKEN: ${{ secrets.GLORIA_INSTANCE_TOKEN }}
        MELMAN_INSTANCE_TOKEN: ${{ secrets.MELMAN_INSTANCE_TOKEN }}
      run: |
        scope-test
